#!/bin/bash

# Example use:
# Build the docker container with `docker build -t 3dgeotop ./3dgeotop`
# Use this script as a command by copying it to your path, eg `/usr/bin/3dgeotop`
# Then do a conversion with eg. `3dgeotop gt2pc sample.csv`

CWD="$(pwd)"

docker run -u "$UID" -w "$CWD" -v "$CWD":"$CWD" --net host -e PYTHONUNBUFFERED=0 3dgeotop "$@"

